---
abstract: 'Mock Object for Net::FTP'
author:
  - 'Takuya Tsuchida <tsucchi at cpan.org>'
build_requires:
  Capture::Tiny: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-Net-FTP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Path: 2.07
  File::Slurp: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tsucchi/Test-Mock-Net-FTP
version: 0.02
